window.__DRAFTS__ = [
  "<%= random('famous') %> <%= random('organizationMember') %> ile iftarda buluştu",
  "<%= random('game') %> oynarken üzerine <%= random('vehicle') %> düşen çocuk yoğun bakımda",
  "<%= random('famous', ['quote', 'towards']) %> <%= random('punishment') %> şoku",
  "Bu görüntü bugün çekildi, gören şok oldu",
  "Ünlü oyuncu twitter hesabından paylaştığı fotoğrafla hayranlarını şaşırttı",
  "<%= random('town', ['quote', 'static']) %> tarihi <%= random('noun') %> bulundu",
  "<%= random('town', ['quote', 'static']) %> <%= random('weapon', ['containing']) %> kavga: <%= random('number') %> yaralı",
  "<%= random('town', ['containing']) %> mucit evde <%= random('noun') %> yaptı",
  "Meteoroloji uyardı, haftasonu <%= random('noun') %> yağabilir",
  "Uzmanlar yanıtladı: <%= random('noun') %> yersek orucumuz bozulur mu?",
  "<%= random('town', ['quote', 'static']) %> yapılan kazıda <%= random('number') %> <%= random('unit') %> <%= random('noun') %> ele geçirildi",
  "<%= random('town', ['containing']) %> bir genç kadın sevgilisini <%= random('weapon') %> ile bıçakladı",
  "Oruçluyken <%= random('noun') %> kokusu nasıl önlenir?",
  "Kayıp <%= random('noun') %> ormanlık alanda <%= random('game') %> oynarken bulundu",
  "<%= random('town', ['quote', 'static']) %> <%= random('famous') %> alarmı",
  "<%= random('town', ['quote', 'static']) %> <%= random('number') %> sene sonra ilk defa <%= random('noun') %> yağdı",
  "<%= random('town', ['quote', 'static']) %> şüpheli <%= random('noun') %> paniği",
  "Hollywood filmlerini aratmayacak görüntüler!",
  "Bu sene zam şampiyonu <%= random('noun') %>",
  "<%= random('weather', ['static']) %> ne yapacağını şaşıran halk asfaltta <%= random('noun') %> pişirdi",
  "Yoğun <%= random('weather') %> yağışı <%= random('vehicle') %> sürücülerini çileden çıkardı",
  "<%= random('town', ['quote', 'static']) %> <%= random('cigar') %> zammı protesto edildi",
  "<%= random('town', ['quote', 'static']) %> bu sabah yapılan operasyonda <%= random('number') %> adet kaçak <%= random('weapon') %> ele geçirildi",
  "<%= random('town', ['quote', 'static']) %> tarım arazilerinde <%= random('bug') %> istilası",
  "<%= random('town', ['quote', 'static']) %> yasağa sinirlenip kepçeyle <%= random('noun') %> yediler",
  "Asfaltta <%= random('noun') %> pişirdiler",
  "Bilim dünyasını şok eden keşif!",
  "<%= random('famous') %> öyle bir şey dedi ki",
  "İşte villada <%= random('game') %> oynarken yakalanan o ünlüler!",
  "Ünlü şarkıcı <%= random('famous') %>, <%= random('game') %> oynayan arkadaşını <%= random('number') %> yerinden bıçakladı"
];

window.__OBJECTS__ = {
  'famous': ['Guido Van Rossum', 'Alva Noto', 'Tom Odell',
             'Evgeny Grinko', 'Kahtalı Mıçı'],
  'game': ['saklambaç', 'körebe', 'halay', 'zeybek', 'seksek', 'piyano', 'kumar'],
  'group': ['veliler', 'emekliler'],
  'organizationMember': ['sevenleri', 'fanları', 'ayranları'],
  'vehicle': ['metrobüs', 'at', 'Tom Odell', 'Evgeny Grinko', 'selfie çubuğu', 'Boeing 777'],
  'punishment': ['idam', 'hapis', 'halay', 'zeybek'],
  'town': ['Burdur', 'Bilecik', 'Ankara', 'Karabük', 'Bolu', 'Samsun', 'Adana', 'Adıyaman'],
  'weapon': ['roketatar', 'muz', 'ak-47', 'gülle', 'Evgeny Grinko', 'nükleer silah', 'selfie çubuğu'],
  'bug': ['lama', 'menemen', 'selfie çubuğu'],
  'noun': [
    'buzdolabı', 'menemen', 'gülle', 'at',
    'muz', 'Tom Odell', 'ak-47', 'roketatar',
    'Macbook Pro', 'sigara', 'Evgeny Grinko',
    'nükleer silah', 'Boeing 777',
    'lama', 'metrobüs', 'selfie çubuğu'
  ],
  'weather': ['kar', 'yağmur', 'sıcak'],
  'cigar': ['sigara', 'pipo tütünü'],
  'number': [4, 8, 15, 16, 23, 42, 78],
  'unit': ['piksel', 'santim']
};

window.__IMAGES__ = {
  'Guido Van Rossum': ['guido.png', 'centered'],
  'Alva Noto': ['alva.png', 'centered'],
  'Tom Odell': ['tom.png', 'centered'],
  'saklambaç': ['saklambac.png', 'cover'],
  'körebe': ['korebe.png', 'cover'],
  'zeybek': ['zeybek.png', 'cover'],
  'halay': ['halay.png', 'cover'],
  'seksek': ['seksek.png', 'cover'],
  'sevenleri': ['birileri.png', 'cover'],
  'fanları': ['fan.png', 'cover'],
  'metrobüs': ['metrobus.png', 'centered'],
  'at': ['at.png', 'centered'],
  'idam': ['idam.png', 'cover'],
  'hapis': ['hapis.png', 'cover'],
  'Burdur': ['burdur.png', 'cover'],
  'Bilecik': ['bilecik.png', 'cover'],
  'Ankara': ['ankara.png', 'cover'],
  'Adana': ['adana.png', 'cover'],
  'Adıyaman': ['adiyaman.png', 'cover'],
  'Karabük': ['karabuk.png', 'cover'],
  'Bolu': ['bolu.png', 'cover'],
  'Samsun': ['samsun.png', 'cover'],
  'veliler': ['veliler.png', 'cover'],
  'piyano': ['piyano.png', 'cover'],
  'emekliler': ['emekliler.png', 'cover'],
  'kar': ['kar.png', 'cover'],
  'roketatar': ['roketatar.png', 'centered'],
  'muz': ['muz.png', 'centered'],
  'ak-47': ['ak-47.png', 'centered'],
  'gülle': ['gulle.png', 'centered'],
  'buzdolabı': ['buzdolap.png', 'centered'],
  'menemen': ['menemen.png', 'centered'],
  'Macbook Pro': ['macbook.png', 'centered'],
  'yumurta': ['yumurta.png', 'centered'],
  'Evgeny Grinko': ['evgeny.png', 'centered'],
  'sigara': ['sigara.png', 'centered'],
  'pipo tütünü': ['pipo.png', 'centered'],
  'hayranları': ['hayran.png', 'cover'],
  'ayranları': ['ayran.png', 'cover'],
  'nükleer silah': ['nukleer.png', 'centered'],
  'lama': ['lama.png', 'centered'],
  'selfie çubuğu': ['selfie.png', 'centered'],
  'Boeing 777': ['b77.png', 'centered'],
  'yağmur': ['piyano.png', 'cover'],
  'sıcak': ['asfalt.png', 'cover'],
  'kumar': ['kumar.png', 'cover'],
  'Kahtalı Mıçı': ['kahtalimici.png', 'centered']
};
